name: Unit Tests

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run unit test
        run: |
          echo 'unit testing ....'
          sleep 600
