name: Unit Tests
on:
  pull_request:
    branches:
      - '*'


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run unit test
        run: |
          echo 'unit testing ....'
          sleep 60
